@echo
if (%1)==(1) goto Sunday
if (%1)==(2) goto Monday
if (%1)==(3) goto Tuesday
if (%1)==(4) goto Wednesday
if (%1)==(5) goto Thursday
if (%1)==(6) goto Friday
if (%1)==(7) goto Saturday
COLOR 0A
:Sunday
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\attachto.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\delete.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\publicvariable.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\scripts.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\selectplayer.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setdamage.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setpos.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\arma2oaserver.RPT" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\server_log.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\mpstatistics.log" "D:\napf\Overpoch_Server\Napf_logs\sunday"
exit
:Monday
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\attachto.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\delete.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\publicvariable.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\scripts.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\selectplayer.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setdamage.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setpos.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\arma2oaserver.RPT" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\server_log.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\mpstatistics.log" "D:\napf\Overpoch_Server\Napf_logs\monday"
exit
:Tuesday
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\attachto.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\delete.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\publicvariable.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\scripts.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\selectplayer.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setdamage.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setpos.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\arma2oaserver.RPT" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\server_log.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\mpstatistics.log" "D:\napf\Overpoch_Server\Napf_logs\Tuesday"
exit
:Wednesday
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\attachto.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\delete.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\publicvariable.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\scripts.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\selectplayer.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setdamage.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setpos.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\arma2oaserver.RPT" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\server_log.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\mpstatistics.log" "D:\napf\Overpoch_Server\Napf_logs\wendsday"
exit
:Thursday
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\attachto.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\delete.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\publicvariable.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\scripts.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\selectplayer.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setdamage.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setpos.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\arma2oaserver.RPT" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\server_log.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\mpstatistics.log" "D:\napf\Overpoch_Server\Napf_logs\thursday"
exit
:Friday
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\attachto.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\delete.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\publicvariable.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\scripts.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\selectplayer.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setdamage.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setpos.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\arma2oaserver.RPT" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\server_log.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\mpstatistics.log" "D:\napf\Overpoch_Server\Napf_logs\friday"
exit
:Saturday
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\addweaponcargo.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\attachto.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\delete.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\publicvariable.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\createvehicle.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\scripts.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\selectplayer.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setdamage.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\BattlEye\setpos.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\HiveExt.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\arma2oaserver.RPT" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\server_log.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
move /y "D:\napf\Overpoch_Server\instance_24_Napf\mpstatistics.log" "D:\napf\Overpoch_Server\Napf_logs\saturday"
exit